added Util object for inferring schema
music-of-the-ainur/almaren-framework pull request #22
Opened 2021-01-19 15:18 UTC by praveenkumarb1207

2021-01-20 13:04 UTC, mantovani requested changes
We also need to add a new section to the documentation.

2021-01-20 13:04 UTC, mantovani commented on src/main/scala/com/github/music/of/the/ainur/almaren/Util.scala
> +  def genDDLFromJsonString(df: DataFrame, field: String): String = {
The "sample" should be coming function's argument.

2021-01-20 13:04 UTC, mantovani commented on src/main/scala/com/github/music/of/the/ainur/almaren/Util.scala
> +  def genDDLFromDataFrame(df: DataFrame): String = {
same here

2021-01-20 14:06 UTC, praveenkumarb1207 commented on src/main/scala/com/github/music/of/the/ainur/almaren/Util.scala
> +  def genDDLFromDataFrame(df: DataFrame): String = {
completed the changes Daniel

2021-01-20 18:21 UTC, mantovani requested changes

2021-01-20 18:21 UTC, mantovani commented on src/main/scala/com/github/music/of/the/ainur/almaren/Util.scala
> +  def genDDLFromJsonString(df: DataFrame, field: String,sampleRatio : Double): String = {
Let's have sampleRatio = 1.0 as default.

2021-01-21 06:47 UTC, praveenkumarb1207 commented on src/main/scala/com/github/music/of/the/ainur/almaren/Util.scala
> +  def genDDLFromJsonString(df: DataFrame, field: String,sampleRatio : Double): String = {
Updated sampleRatio = 1.0 as default.

2021-01-21 11:58 UTC, mantovani approved these changes

2021-01-21 11:58 UTC, merged