added repartition with column and its unit test #30
music-of-the-ainur/almaren-framework pull request #31
Opened 2021-06-24 15:27 UTC by praveenkumarb1207

2021-06-24 18:34 UTC, mantovani requested changes

2021-06-24 18:34 UTC, mantovani commented on src/main/scala/com/github/music/of/the/ainur/almaren/builder/core/Main.scala
> +  def repartitionWithColumn(size: Int,partitionExprs:Column*): Option[Tree] =
Just call it repartition and add other column..., it's called method overload:

```
  def repartition(size:Int, partitionExprs:Column*): Option[Tree] =
     Repartition(size, partitionExprs)
```

2021-06-25 07:14 UTC, praveenkumarb1207 commented
requested changes done

2021-06-28 14:20 UTC, mantovani approved these changes

2021-06-28 14:20 UTC, merged