Added Target File Code and Test Cases
music-of-the-ainur/almaren-framework pull request #39
Opened 2022-03-21 12:57 UTC by badrinathpatchikolla

2022-03-21 17:05 UTC, mantovani requested changes

2022-03-21 17:05 UTC, mantovani commented on src/main/scala/com/github/music/of/the/ainur/almaren/state/core/Target.scala
> +      write.saveAsTable(tableName.getOrElse(throw new Exception("tableName not provided")))
saveAsTable is optional, not mandatory.

```scala
tableName match {
    case Some(tbName) => write.salveAsTable(tbName)
    case None => write.save
}
```

2022-03-21 17:55 UTC, badrinathpatchikolla commented on src/main/scala/com/github/music/of/the/ainur/almaren/state/core/Target.scala
> +      write.saveAsTable(tableName.getOrElse(throw new Exception("tableName not provided")))
Added Case statement for tablename

2022-03-28 15:01 UTC, mantovani approved these changes

2022-03-28 15:01 UTC, merged